# Generated by Django 4.2.26 on 2025-11-15 20:28

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name (1-100 characters)",
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name (1-100 characters)",
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Unique email address",
                        max_length=254,
                        unique=True,
                        validators=[api.models.validate_email],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "persons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name (1-150 characters)",
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(150),
                        ],
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique SKU (3-50 characters)",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price (≥ 0, 2 decimal places)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional owner (Person)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="api.person",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="persons_email_768727_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["last_name"], name="persons_last_na_312bc6_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["created_at"], name="persons_created_6ba3d4_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_price_fe467e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="products_created_e1ba5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
    ]
